- hosts: server
  gather_facts: no
  become: false

  tasks:
    - name: clone app repository
      git:
        repo: git@github.com:nplyusnin/courses-app-rails.git
        dest: /apps/courses-app-rails
        accept_hostkey: yes
